version: "3.3"

services:
  linux:
    image: nginx:latest
    networks:
      - private
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints: [node.platform.os==linux]
  windows:
    image: microsoft/iis
    networks:
      - private
    deploy:
      replicas: 2
      endpoint_mode: dnsrr
      placement:
        constraints: [node.platform.os==windows]

networks:
  private:
